### ISSUE TITLE
my-dev-portal Failed to compile for production build

### ISSUE THREAD

**Issue by fabidi-tr** [Moesif/moesif-developer-portal#51]
Hi folks!

node: v18.19.0
npm: 10.2.3

For the my-dev-portal UI project, I am able to run 'npm start' just fine, I can see the dev portal launch in the browser.

When I try 'npm run build' I get the following output error

```
Failed to compile.

The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script

```

Verbose output:

```
my-dev-portal git:(develop) ✗ npm run build --loglevel verbose

npm verb cli /home/myusername/.nvm/versions/node/v18.19.0/bin/node /home/myusername/.nvm/versions/node/v18.19.0/bin/npm
npm info using npm@10.2.3
npm info using node@v18.19.0
npm verb title npm run build
npm verb argv "run" "build" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/home/myusername/.npm/_logs/2023-12-29T09_03_20_519Z-
npm verb logfile /home/myusername/.npm/_logs/2023-12-29T09_03_20_519Z-debug-0.log

> my-dev-portal@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script


npm verb exit 1
npm verb code 1
```

### What have I tried to solve this
I have of course googled the misc forums, and tried ChatGPT to find the answer. Several people have encountered this error, but their solutions were specific to their own projects.

**Comment by xinghengwang** [comment]
Try this: 

https://github.com/Moesif/moesif-developer-portal/blob/0d41f689b626ab022ddd66aa6e70283d2ff4eb29/my-dev-portal/package.json#L42

In this line change to :

```
    "production": [
      ">2%"
    ],
```

This should target any browser than have more than 2% market share.

**Comment by fabidi-tr** [comment]
That worked! Thank you
