### ISSUE TITLE
Configured my-dev-portal and my-dev-portal-api, but blank screen showing on http://127.0.0.1:4000/

### ISSUE THREAD

**Issue by ravineshappypie** [Moesif/moesif-developer-portal#57]
Configured Moesif account with AWS.
Downloaded developer portal using the git. 
Using Node Version 16.15.1

created .env file in my-dev-portal, my-dev-portal-api and my-dev-portal-authorizer by copying .env.template

I did one change in my-dev-portal-api/.env, that is MOESIF_APPLICATION_ID="your Moesif application ID"

my-dev-portal-api is running fine
my-dev-portal is running but showing a black blank screen.

While on cli it is showing like:

Compiled successfully!

You can now view my-dev-portal in the browser.

  http://127.0.0.1:4000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully

**Comment by ravineshappypie** [comment]
I have checked this with Node v18.19.0. Same issue

**Comment by kingsleyh** [comment]
I had the same issue - It was not until I set Auth0 as the auth provider and then setup an auth0 account and put the env vars for auth0 in the .env files - now I am presented with the dev portal welcome screen - however the signup/login doesn't work I get a service non found error.

**Comment by xinghengwang** [comment]
How did you get the service not found error? You have a screenshot?

**Comment by xinghengwang** [comment]
The service not found issue is mostly due to 

https://community.auth0.com/t/how-to-troubleshoot-access-denied-due-to-service-not-found-error/6822/2

You may have to create an service in Auth0 that matches the "audience" referenced here

```
          audience: process.env.REACT_APP_DEV_PORTAL_API_SERVER,
````

**Comment by kingsleyh** [comment]
got it all working now thanks :)
